### ISSUE TITLE
打开一个无响应的串口时程序出现假死

### ISSUE THREAD

**Issue by caoqiang250** [junhuanchen/mpfshell-lite#5]
当程序去打开一个无法连接的串口时（例如windows电脑自带的COM1），程序会连接不上，并一直不主动推出，手动ctrl+C手动退出也无效，建议加一个连接超时时间参数，可以在open后指定；在指定时间内连接不上就算连接失败，程序返回错误，然后主动退出(bug 出现在win10系统上)

**Comment by junhuanchen** [comment]
嗯，以前我也考虑过，这个暂时可以自己直接修改 py 源码实现，我以前也想加一个动态的 timeout 参数作为可选

**Comment by caoqiang250** [comment]
嗯，这个最好加一下，不过我 在指令命令行的逻辑处加入了 超时操作，oepn操作2S内还没有退出，我会强行杀死这个进程。
