### ISSUE TITLE
点开就报错

### ISSUE THREAD

**Issue by jack2nb** [junhuanchen/mpfshell-lite#7]
-- Running on Python 3.5 using PySerial 3.3 --

mpfs [/]> open com5

('exception', b'', b'Traceback (most recent call last):\r\n  File "<stdin>", line 1, in <module>\r\nImportError: no module named \'ubinascii\'\r\n')

**Comment by junhuanchen** [comment]
你板子里的固件没有编译 ubinascii 或 binascii ，这是传输代码用的。
